### ISSUE TITLE
Missing closing tags for label

### ISSUE THREAD

**Issue by travisdowns** [willymcallister/willymcallister.github.io#123]
Hi Willy,

I am using your nested comments implementation for basis as my own (with attribution, etc), and ran into some funky parsing issues which boiled down to missing close tags for `<label>` in `comments_form.html`. 

E.g., [this tag](https://github.com/willymcallister/willymcallister.github.io/blob/master/_includes/comment_form.html#L27) is never closed, and some others in the file.

More an FYI than anything :).

**Comment by willymcallister** [comment]
Closing </label> tags in comment_form.html fixed and committed.
